"""initial schema

Revision ID: 63d32cd7621a
Revises:
Create Date: 2026-06-01 15:13:55.244468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d32cd7621a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_hash', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('prev_hash', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('merkle_root', sa.String(length=100), nullable=False),
    sa.Column('proof_of_work', sa.BigInteger(), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('prev_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prev_id'], ['block.id'], name=op.f('fk_block_block_prev_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block'))
    )
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_block_hash'), ['block_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_block_idx'), ['idx'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_prev_hash'), ['prev_hash'], unique=False)

    op.create_table('chain_fill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_fill'))
    )
    op.create_table('pending_txn',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('txid', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('json_data', sa.Text(), nullable=False),
    sa.Column('received', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_txn'))
    )
    with op.batch_alter_table('pending_txn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_txn_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_txn_txid'), ['txid'], unique=True)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('txid', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('public_key', sa.String(length=700), nullable=True),
    sa.Column('signature', sa.String(length=700), nullable=True),
    sa.Column('prev_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction'))
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_txid'), ['txid'], unique=True)

    op.create_table('block_transaction',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], name=op.f('fk_block_transaction_block_block_id')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_block_transaction_transaction_transaction_id')),
    sa.PrimaryKeyConstraint('block_id', 'transaction_id', name=op.f('pk_block_transaction'))
    )
    op.create_table('chain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_hash', sa.String(length=100), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], name=op.f('fk_chain_block_block_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain'))
    )
    with op.batch_alter_table('chain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chain_block_hash'), ['block_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_chain_block_id'), ['block_id'], unique=False)

    op.create_table('chain_fill_block',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_hash', sa.String(length=100), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('block_json', sa.Text(), nullable=True),
    sa.Column('chain_fill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chain_fill_id'], ['chain_fill.id'], name=op.f('fk_chain_fill_block_chain_fill_chain_fill_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_fill_block'))
    )
    op.create_table('longest_chain_block',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], name=op.f('fk_longest_chain_block_block_block_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id', name=op.f('pk_longest_chain_block')),
    sa.UniqueConstraint('position', name=op.f('uq_longest_chain_block_position'))
    )
    op.create_table('outflow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('txid', sa.String(length=100), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('opposition', sa.String(length=500), nullable=True),
    sa.Column('rescind', sa.String(length=500), nullable=True),
    sa.Column('support', sa.String(length=500), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_outflow_transaction_transaction_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outflow')),
    sa.UniqueConstraint('txid', 'idx', name=op.f('uq_outflow_txid'))
    )
    with op.batch_alter_table('outflow', schema=None) as batch_op:
        batch_op.create_index('ix_outflow_txid_idx', ['txid', 'idx'], unique=False)

    op.create_table('inflow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('txid', sa.String(length=100), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('outflow_txid', sa.String(length=100), nullable=False),
    sa.Column('outflow_idx', sa.Integer(), nullable=False),
    sa.Column('outflow_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outflow_id'], ['outflow.id'], name=op.f('fk_inflow_outflow_outflow_id')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_inflow_transaction_transaction_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inflow')),
    sa.UniqueConstraint('txid', 'idx', name=op.f('uq_inflow_txid'))
    )
    with op.batch_alter_table('inflow', schema=None) as batch_op:
        batch_op.create_index('ix_inflow_txid_idx', ['txid', 'idx'], unique=False)

    op.create_table('pending_ioflow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('txid', sa.String(length=100), nullable=False),
    sa.Column('outflow_txid', sa.String(length=100), nullable=False),
    sa.Column('outflow_idx', sa.Integer(), nullable=False),
    sa.Column('pending_txn_id', sa.Integer(), nullable=False),
    sa.Column('outflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outflow_id'], ['outflow.id'], name=op.f('fk_pending_ioflow_outflow_outflow_id')),
    sa.ForeignKeyConstraint(['pending_txn_id'], ['pending_txn.id'], name=op.f('fk_pending_ioflow_pending_txn_pending_txn_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_ioflow'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_ioflow')
    with op.batch_alter_table('inflow', schema=None) as batch_op:
        batch_op.drop_index('ix_inflow_txid_idx')

    op.drop_table('inflow')
    with op.batch_alter_table('outflow', schema=None) as batch_op:
        batch_op.drop_index('ix_outflow_txid_idx')

    op.drop_table('outflow')
    op.drop_table('longest_chain_block')
    op.drop_table('chain_fill_block')
    with op.batch_alter_table('chain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chain_block_id'))
        batch_op.drop_index(batch_op.f('ix_chain_block_hash'))

    op.drop_table('chain')
    op.drop_table('block_transaction')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_txid'))

    op.drop_table('transaction')
    with op.batch_alter_table('pending_txn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_txn_txid'))
        batch_op.drop_index(batch_op.f('ix_pending_txn_timestamp'))

    op.drop_table('pending_txn')
    op.drop_table('chain_fill')
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_prev_hash'))
        batch_op.drop_index(batch_op.f('ix_block_idx'))
        batch_op.drop_index(batch_op.f('ix_block_block_hash'))

    op.drop_table('block')
    # ### end Alembic commands ###
